version: '3.8'

services:
  db:
    build: ./DB_init
    ports:
      - "1433:1433"
  
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mssql+pyodbc://sa:YourStrong!Passw0rd@db/RecipeAppDB?driver=ODBC+Driver+17+for+SQL+Server"
    depends_on:
      - db
    restart: always

